name: fantasy_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  sqflite: ^2.0.0+3
  path: ^1.9.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/otros/logo.png"
  adaptive_icon_foreground: "assets/otros/logo.png" # Set the foreground image (same or different from image_path)
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/jugadores_v2.db
    - assets/flags/
    - assets/escudos/
    - assets/otros/
